# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}

    strategy:
      matrix:
        node-version: [18.x, 19.x]
        mongodb-version: ["5.0", "6.0"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Create env vars
        run: |
          mkdir config
          echo "MONGODB_URI=$TEST_MONGODB_URI" > config/.env.test
          cat config/.env.test

      - name: Install dependencies
        run: npm i

      - name: Running tests
        run: npm test
