# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Start MongoDB 6.0
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: "6.0"

      - name: Create env vars
        run: |
          mkdir config
          echo "MONGODB_URI=$TEST_MONGODB_URI" > config/.env.test
          cat config/.env.test

      - name: Install dependencies
        run: npm i

      - name: Running tests
        run: npm test
